name: Download from S3

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the workflow when there is a push to the main branch

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download file from S3
      run: |
        aws s3 cp s3://tneelb/BCWC/msw_in_region_disposal.xlsx folder/
