name: Download File from Dell ECS and Commit to Repo

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  download_file:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # You can specify the Python version here

    # Step 3: Install the dependencies (e.g., boto3)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    # Step 4: Run the Python script to download the file from Dell ECS
    - name: Download file from Dell ECS
      run: |
        python download_from_dell_ecs.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    # Step 5: Add, commit, and push the downloaded file to the repository
    - name: Commit and push downloaded file to repository
      run: |
        git config --global user.name "AmanBhathal"
        git config --global user.email "amandeep.bhathal@gov.bc.ca"
        git add /folder/msw_in_region_disposal.xlsx  # Add the downloaded file (path relative to the repo root)
        git commit -m "Add downloaded file from Dell ECS"
        git push origin main  # Push to the main branch
