name: Run Python Script

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  run-python:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 constants

    - name: Run Python script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        
      run: |
        python listfiles.py  # Replace with the name of your Python script

    - name: Download file from S3
      run: |
        git config --global user.name "AmanBhathal"
        git config --global user.email "amandeep.bhathal@gov.bc.ca"
        git add /folder/msw_in_region_disposal.xlsx  # Add the downloaded file (path relative to the repo root)
        git commit -m "Add file from S3 to GitHub repo"
        git push origin main  # Push the changes to the repo
