name: Run Python Script

on:
  push:
    branches:
      - main  # This triggers the action when there's a push to the main branch
  pull_request:
    branches:
      - main  # This triggers the action when a PR is opened/updated for the main branch

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Choose the runner type (e.g., ubuntu-latest, windows-latest, etc.)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        #pip install -r requirements.txt    # Install dependencies (if you have a requirements.txt)

    - name: Run Python script
      run: python test.py  # Replace 'your_script.py' with the name of your Python script

    - name: Upload results (optional)
      if: success()  # Upload results if the script runs successfully
      run: echo "Script finished successfully"
